[2025-06-10T22:52:57.744+0700] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-10T22:52:57.808+0700] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: earthquake_data_ingestion.check_api_connectivity manual__2025-06-10T15:52:48+00:00 [queued]>
[2025-06-10T22:52:57.833+0700] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: earthquake_data_ingestion.check_api_connectivity manual__2025-06-10T15:52:48+00:00 [queued]>
[2025-06-10T22:52:57.835+0700] {taskinstance.py:2856} INFO - Starting attempt 1 of 3
[2025-06-10T22:52:57.879+0700] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): check_api_connectivity> on 2025-06-10 15:52:48+00:00
[2025-06-10T22:52:57.892+0700] {standard_task_runner.py:72} INFO - Started process 16926 to run task
[2025-06-10T22:52:57.906+0700] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'earthquake_data_ingestion', 'check_api_connectivity', 'manual__2025-06-10T15:52:48+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/ingestion.py', '--cfg-path', '/tmp/tmp8ltbpre4']
[2025-06-10T22:52:57.915+0700] {standard_task_runner.py:105} INFO - Job 7: Subtask check_api_connectivity
[2025-06-10T22:52:58.109+0700] {task_command.py:467} INFO - Running <TaskInstance: earthquake_data_ingestion.check_api_connectivity manual__2025-06-10T15:52:48+00:00 [running]> on host DESKTOP-1U3MHTH.
[2025-06-10T22:52:58.414+0700] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='magnitudr-team' AIRFLOW_CTX_DAG_ID='earthquake_data_ingestion' AIRFLOW_CTX_TASK_ID='check_api_connectivity' AIRFLOW_CTX_EXECUTION_DATE='2025-06-10T15:52:48+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-10T15:52:48+00:00'
[2025-06-10T22:52:58.420+0700] {taskinstance.py:731} INFO - ::endgroup::
[2025-06-10T22:52:58.883+0700] {ingestion.py:59} INFO - üîç Checking USGS API connectivity...
[2025-06-10T22:52:59.801+0700] {ingestion.py:78} INFO - ‚úÖ API connectivity OK - Found 1 test records
[2025-06-10T22:52:59.805+0700] {python.py:240} INFO - Done. Returned value was: True
[2025-06-10T22:52:59.901+0700] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-06-10T22:52:59.905+0700] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=earthquake_data_ingestion, task_id=check_api_connectivity, run_id=manual__2025-06-10T15:52:48+00:00, execution_date=20250610T155248, start_date=20250610T155257, end_date=20250610T155259
[2025-06-10T22:52:59.971+0700] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2025-06-10T22:53:00.079+0700] {taskinstance.py:3891} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-06-10T22:53:00.089+0700] {local_task_job_runner.py:240} INFO - ::endgroup::
